config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :weekly_status

  get 'admin_upload/index'
  post  "admin_upload" =>'admin_upload#upload'

  get 'project_mgr/index'
  post  "project_mgr/summaries" =>'project_mgr#summaries'


  get  "weekly_status_index" =>'weekly_status#index'

  match '/weekly_status_details/:id' => 'weekly_status#details', via: :get
  post  "magic_upload" =>'weekly_status#magic_upload'
  post  "weekly_status_upload" =>'weekly_status#upload'

  patch  "weekly_summary_update" =>'weekly_status#update'

  devise_for :users
  post 'fetch_time' => 'react_component#fetch_time'

  %w(account rec_engine).each { |path|
    get "/#{path}" => 'react_component#auth'
  }


  %w(awaiting_approval).each { |path|
    get "/#{path}" => 'react_component#awaiting_approval'
  }


  root :to => 'layouts#root'

end

app/controllers/project_mgr_controller.rb
class ProjectMgrController < ApplicationController
  # Check that the user has the right authorization to access clients.
  before_action :verify_user_in_role!, except: [:get_project_tasks]
  before_action :init_dropdown_defaults

  init_dropdown_defaults_roles(RoleTags::PM_ROLE, RoleTags::SENIOR_PM_ROLE)
  def init_dropdown_defaults
    @project_title = params[:project_title] ||= ''
    @task_name = params[:task_name] ||= 'all'
    @wsd = params[:week_start_date] ||= ''
    @task_options = helpers.convert_distinct_tasks[@project_title].to_a
  end


  index_roles(RoleTags::PM_ROLE, RoleTags::SENIOR_PM_ROLE)
  def index
    @summaries = nil
  end

  summaries_roles(RoleTags::PM_ROLE, RoleTags::SENIOR_PM_ROLE)
  def summaries
    @summaries = WeeklySummary.retrieve_pm_summaries(project_title: @project_title, task_name: @task_name, week_start_date: @wsd)
    render project_mgr_index_path
  end
end

app/helpers/project_mgr_helper.rb
module ProjectMgrHelper
  # used with options_for_select to load the weekly_start_dates drop down
  def week_start_date_options
    ProjectHelper.distinct_weekly_start_dates.inject([]) do |ret, wsd|
      ret << ["#{wsd['week_start_date'].strftime("%m/%d/%Y")} through #{(wsd['week_start_date'] + 6).strftime("%m/%d/%Y")}", wsd['week_start_date']]; ret
    end
  end

  def convert_distinct_tasks
    titles = {}
    ProjectHelper.distinct_task_names.each do |e|
      titles[e.timesheet_cell_project_title] ||= []
      titles[e.timesheet_cell_project_title] << e.timesheet_cell_task_name
    end
    titles
  end
end

app/views/project_mgr/index.html.erb
<div class="container">
  <h4>PM Weekly Summaries Filter</h4>
  <div class="w-50">
    <%= form_tag project_mgr_summaries_path, method: :post do %>
      <div class="form-group">
        <label for="project_title">Project Title:</label>
        <%= select_tag "project_title",
                       options_for_select(
                           select_options(
                               ProjectHelper.distinct_project_titles,
                               default_text: '--- Select a project ---',
                               default_value: '',
                               value_prop: :timesheet_cell_project_title,
                               text_prop: :timesheet_cell_project_title),
                           @project_title), {:class => 'form-control', :onchange => 'project_title_change()'} %>
      </div>
      <div class="form-group">
        <label for="task_name">Task Name:</label>
        <%= select_tag "task_name", options_for_select(@task_options, @task_name), {:class => 'form-control'} %>
      </div>
      <div class="form-group">
        <label for="week_start_date">Week Start/End:</label>
        <%= select_tag "week_start_date", options_for_select(week_start_date_options, @wsd), {:class => 'form-control'} %>
      </div>
      <%= submit_tag("Retrieve Weekly Summaries", :id => "submit_button", :class => "btn btn-primary", :name => "submit_button") %>
    <% end %>
  </div>
  <hr>
  <br>
  <% if @summaries %>
    <h3>Weekly Summary Results</h3>
    <%= "No results found." if @summaries.empty? %>
    <% @summaries.each do |summary| %>
      <% summary_status = summary.weekly_status.summary_status %>
      <% status = fetch_summary_status summary.weekly_status %>
      <% icon = "fas fa-#{status[:image]}" %>

      <div class="container">
        <div class="row">
          <div class="col-sm-6">
            <%= summary.person_email_id %><br>
            <%= summary.timesheet_cell_task_name %><br>
            <i class="<%= icon %>"></i>&nbsp;&nbsp;<span style="font-weight: bold; <%= "color: #{status[:color]}" %>"><%= status[:status] %></span><br>
          </div>
          <div class="col-sm-6">
            <% if summary_status.eql?(WeeklyStatus::COMPLETED.to_s) %>
              <b>Weekly
                Summary:</b><br><%= text_area_tag 'weekly_summary_comment', summary.weekly_summary_comment, class: 'summary-text-area', disabled: true %>
              <br><b>Blockers:</b><br><%= text_area_tag 'weekly_summary_blockers', summary.blockers, class: 'summary-text-area', disabled: true %>
              <br><b>Next Planned
            Activity:</b><br><%= text_area_tag 'weekly_summary_next_planned_activity', summary.next_planned_activity, class: 'summary-text-area', disabled: true %>
            <% end %>
          </div>
        </div>
      </div>
      <hr>
    <% end %>
  <% end %>
</div>
<script type="text/javascript" charset="utf-8">
    var project_titles_to_tasks = <%= raw convert_distinct_tasks.to_json%>;

    let project_title_change = () => {
        const {target} = event;
        const value = target.value;
        const disable_submit = (value === '');

        filter_tasks(value);
        $('#submit_button').prop('disabled', disable_submit);
    };

    let filter_tasks = (project_title) => {
        let tasks = project_titles_to_tasks[project_title];
        let dropdown = $('#task_name');
        let default_option = '<option disabled selected value="all">--- Select a Project to Filter By ---</option>';

        if (project_title !== '') {
            default_option = '<option value="all">--- All Tasks ---</option>';
        }
        dropdown.empty();
        dropdown.append(default_option);

        if (project_title !== '') {
            tasks.forEach(function (task) {
                dropdown.append($('<option></option>').attr('value', task).text(task));
                $("select#task_name option[value='<%=@task_name %>']").attr('selected', 'selected');
            })
        }
    };
    $(document).ready(function(){
        $('#submit_button').prop('disabled', ($('#project_title').val() === ''));
        <% if @project_title.empty? %>
        let dropdown = $('#task_name');
        let default_option = '<option disabled selected value="all">--- Select a Project to Filter By ---</option>';
        dropdown.append(default_option);
        <% end %>

    });
</script>