config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :weekly_status

  get 'admin_upload/index'
  post  "admin_upload" =>'admin_upload#upload'

  get 'project_mgr/index'
  post  "project_mgr/summaries" =>'project_mgr#summaries'


  get  "weekly_status_index" =>'weekly_status#index'

  match '/weekly_status_details/:id' => 'weekly_status#details', via: :get
  post  "magic_upload" =>'weekly_status#magic_upload'
  post  "weekly_status_upload" =>'weekly_status#upload'

  patch  "weekly_summary_update" =>'weekly_status#update'

  devise_for :users
  post 'fetch_time' => 'react_component#fetch_time'

  %w(account rec_engine).each { |path|
    get "/#{path}" => 'react_component#auth'
  }


  %w(awaiting_approval).each { |path|
    get "/#{path}" => 'react_component#awaiting_approval'
  }


  root :to => 'layouts#root'

end

app/controllers/admin_upload_controller.rb
class AdminUploadController < ApplicationController
  # Check that the user has the right authorization to access clients.
  before_action :verify_user_in_role!

  index_roles(RoleTags::ADMIN_ROLE)
  def index
    @uploads = UnanetCsvUpload.all.order(created_at: :desc, end_date: :desc)
  end

  #upload_roles(RoleTags::ADMIN_ROLE, RoleTags::PM_ROLE)
  upload_roles(RoleTags::ADMIN_ROLE)
  def upload
    csv_holder = UnanetCsvUpload.new
    upload_start_date, upload_end_date = nil, nil

    if !params[:file].nil?
      file = params[:file]
      csv_holder.csv_upload.attach(io: file.tempfile, filename: file.original_filename)
      csv_holder.user_email = current_user.email

      WeeklyStatus.transaction do
        big_csv = csv_holder.get_csv
        buckets_of_csv = Unanet.trim_future(Unanet.bucket_csv big_csv)
        buckets_of_csv.keys.each do |bucket|
          start_of_week = bucket.first
          email = bucket.last
          weekly_user_csv = buckets_of_csv[bucket]

          # set the  upload_start_date and upload_end_date based on the user bucket being processed
          upload_start_date ||= start_of_week
          upload_end_date = start_of_week

          # create or update the WeeklyStatus record and their associate detail records
          ws = WeeklyStatus.where(user_email: email, week_start_date: start_of_week).first_or_initialize
          ws.csv_data = weekly_user_csv
          ws.save!
          if ws.local_details
            ws.local_details.each(&:save!)

            # create the summary record based on the newly saved details
            summaries = init_weekly_summary(ws.id)
            summaries.each(&:save!)
          end

        end
        # save the upload record
        csv_holder.start_date = upload_start_date
        csv_holder.end_date = upload_end_date
        csv_holder.save!
        flash[:notice] = "CSV uploaded successfully!"

        #  blank out the project titles and weekly start dates (used to load drop downs on pm page)
        ProjectHelper.distinct_project_titles = WeeklyStatusDetail.distinct_project_titles
        ProjectHelper.distinct_weekly_start_dates = WeeklyStatus.distinct_start_of_week(:desc)
        ProjectHelper.distinct_task_names = WeeklyStatusDetail.distinct_task_names
      end
    else
      flash[:alert] = "Please select a file to upload"
    end

    redirect_to admin_upload_index_path
  end

  private

  def init_weekly_summary(ws_id)
    summaries = WeeklyStatus.weekly_summary(ws_id)
    summaries_array = []
    summaries.each do |ws|
      summaries_array << WeeklySummary.new(ws)
    end
    summaries_array
  end

=begin
  def magic_upload
    username = params['unanet-username-input']
    pwd = params['unanet-password-input']
    url = params['unanet-url-input']
    begin
      fetcher = Unanet::FetchSummaries.new(username, pwd)
      summaries = fetcher.get_report
    rescue => e
      $log.error(LEX('Failed to instantiate FetchSummaries', e))
      summaries = nil
    end

    @result = 'sad'
    @headers = []
    @rows = []

    if (summaries&.success)
      @result = 'happy'
      @headers = summaries.csv[summaries.csv.keys[-3]].headers
      @rows = summaries.csv[summaries.csv.keys[-3]].by_row

      summaries.csv.keys.each do |weekly_person_bucket|
        start_of_week = weekly_person_bucket.first
        start_process_date = Unanet::FetchSummaries::LOOKBACK_WEEKS.weeks.ago
        next if start_of_week < start_process_date
        next if start_of_week > Unanet.get_start_of_week(Time.now.to_date)
        email = weekly_person_bucket.last
        csv = summaries.csv[weekly_person_bucket]
        ws = WeeklyStatus.where(user_email: email, week_start_date: start_of_week).first_or_initialize
        ws.csv_magic = csv

        WeeklyStatus.transaction do
          ws.save!
          ws.local_details.each do |detail|
            detail.save!
          end
        end
      end
    end
    redirect_to weekly_status_index_path
  end

  def upload
    csv_holder = UnanetCsvUpload.new
    upload_start_date, upload_end_date = nil, nil

    if !params[:file].nil?
      file = params[:file]
      csv_holder.csv_upload.attach(io: file.tempfile, filename: file.original_filename)
      csv_holder.user_email = current_user.email

      big_csv = csv_holder.get_csv
      buckets_of_csv = Unanet.bucket_csv big_csv

      WeeklyStatus.transaction do
        buckets_of_csv.keys.each do |bucket|
          start_of_week = bucket.first
          email = bucket.last
          weekly_user_csv = buckets_of_csv[bucket]

          # set the  upload_start_date and upload_end_date based on the user bucket being processed
          upload_start_date ||= start_of_week
          upload_end_date = start_of_week

          # create or update the WeeklyStatus record and their associate detail records
          ws = WeeklyStatus.where(user_email: email, week_start_date: start_of_week).first_or_initialize
          ws.csv_data = weekly_user_csv
          ws.save!

          # save the local details todo why the if statement?
          if ws.local_details
            ws.local_details.each(&:save!)
          end

          $log.error("**********************************************")
          # create the summary record based on the newly saved details
          init_weekly_summary(ws.id)
        end

        # save the upload record
        csv_holder.start_date = upload_start_date
        csv_holder.end_date = upload_end_date
        csv_holder.save!
      end
    else
      flash[:alert] = "Please select a file to upload"
    end

    redirect_to weekly_status_index_path
  end
=end
end

app/views/admin_upload/index.html.erb
<div class="container">
  <h3>Timesheet CSV Upload</h3>
  <%= form_tag admin_upload_path, method: :post, multipart: true do %>
    <div class="form-group">
      <label for="file">Select CSV File to Upload:</label>
      <%= file_field_tag "file", class: 'form-control-file' %><br>
      <%= submit_tag("Upload CSV File", :id => "button", :class => "btn btn-primary", :name => "submit") %>
    </div>
  <% end %>
  <hr>
  <br>
  <h3>Previous Uploads</h3>
  <table class="table" style="width: fit-content">
    <thead class="thead-light">
    <tr>
      <th>Upload Date</th>
      <th>Uploaded By User</th>
      <th>Week Start Date</th>
      <th>Week End Date</th>
      <th>Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= upload.created_at.localtime.strftime("%m/%d/%Y at %H:%M:%S") %></td>
        <td><%= upload.user_email %></td>
        <td><%= upload.start_date %></td>
        <td><%= upload.end_date + 6 %></td>
        <td><%= link_to 'Download CSV', rails_blob_path(upload.csv_upload, disposition: 'attachment') %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<!-- Modal -->
<!--
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Retrieve Unanet Timecard Data</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%#= form_tag magic_upload_path, method: 'post' do %>
          <div class="form-group">
            <label for="unanet-username-input">Unanet Username:</label>
            <input type="text" id="unanet-username-input" name="unanet-username-input" placeholder="Enter your Unanet username">
          </div>
          <div class="form-group">
            <label for="unanet-password-input">Unanet Password</label>
            <input type="password" name="unanet-password-input" id="unanet-password-input" placeholder="Enter your Unanet password">
          </div>
          <div class="form-group">
            <label for="unanet-url-input">Unanet Report URL</label><br>
            <input type="url" name="unanet-url-input" id="unanet-url-input" placeholder="Enter your Unanet report url">
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
            <button type="submit" id='btn-submit-form' class="btn btn-primary">Retrieve Unanet Timecards</button>
          </div>
        <%# end %>
      </div>
    </div>
  </div>
</div>
-->
<!--  <script type="text/javascript" charset="utf-8">-->
<!--      $("#btn-submit-form").click(function () {-->
<!--          let data = $("#unanet-login").serialize();-->
<!--          const token = $('meta[name="csrf-token"]').attr('content');-->
<!--          console.log("data is ", data);-->
<!--          $.ajax({-->
<!--              url: gon.routes['magic_upload_path'],-->
<!--              type: "POST",-->
<!--              data: data,-->
<!--              headers: {-->
<!--                  'X-Requested-With': 'XMLHttpRequest',-->
<!--                  'X-CSRF-Token': token-->
<!--              },-->
<!--              success: function (data, textStatus, jqXHR) {-->
<!--                  console.log("response with ", data);-->
<!--                  $('#ajax_results').text(data);-->
<!--              },-->
<!--              error: function (jqXHR, textStatus, errorThrown) {-->
<!--                  console.log("error response", textStatus);-->
<!--              }-->
<!--          });-->
<!--      });-->
<!--  </script>-->