config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :weekly_status

  get 'admin_upload/index'
  post  "admin_upload" =>'admin_upload#upload'

  get 'project_mgr/index'
  post  "project_mgr/summaries" =>'project_mgr#summaries'


  get  "weekly_status_index" =>'weekly_status#index'

  match '/weekly_status_details/:id' => 'weekly_status#details', via: :get
  post  "magic_upload" =>'weekly_status#magic_upload'
  post  "weekly_status_upload" =>'weekly_status#upload'

  patch  "weekly_summary_update" =>'weekly_status#update'

  devise_for :users
  post 'fetch_time' => 'react_component#fetch_time'

  %w(account rec_engine).each { |path|
    get "/#{path}" => 'react_component#auth'
  }


  %w(awaiting_approval).each { |path|
    get "/#{path}" => 'react_component#awaiting_approval'
  }


  root :to => 'layouts#root'

end

app/models/weekly_status.rb
require 'date'
require './lib/unanet/UnanetReports'

class WeeklyStatus < ApplicationRecord
  include Unanet::Reports::Columns

  NOT_STARTED = :not_started
  IN_PROCESS = :in_process
  COMPLETED = :completed
  enum summary_status: {NOT_STARTED => 0, IN_PROCESS => 1, COMPLETED => 2}

  before_create :create_details
  has_many :weekly_status_details, dependent: :destroy
  has_many :weekly_summaries, dependent: :destroy
  attr_accessor :local_details
  attr_accessor :csv_data
  accepts_nested_attributes_for :weekly_summaries, allow_destroy: true

  # scope to get the list of weekly status weeks (pass :asc or :desc for sort order)
  # example:  WeeklyStatus.distinct_start_of_week(:asc)
  scope :distinct_start_of_week, -> (order_asc_desc) { select(:week_start_date).distinct.order(week_start_date: order_asc_desc) }

  def self.latest_start_of_week(start_of_week, user)
    WeeklyStatus.where("week_start_date = ? and user_id = ? and active = true", WeeklyStatus.get_start_of_week(start_of_week), user.id)
  end

  def reviewed_status!
    all_reviewed = true
    weekly_summaries.each do |summary|
      unless summary.reviewed
        all_reviewed = false
        break
      end
    end
    all_reviewed ? completed! : in_process!
  end

  def WeeklyStatus.build_summary_row(row)
    # get the intersection of columns from details with the columns in the summary table
    s = WeeklySummary.column_names
    d = WeeklyStatusDetail.column_names
    cols = d & s - ['id']

    # get the detail row data as json and include the intersection columns so that it maps like the summary table
    summary_row = row.as_json
    summary_row.slice!(*cols)

    # aggregate the comments and return the summary row
    summary_row['weekly_summary_comment'] = "#{row.timesheet_cell_work_date.to_s}: #{row.timesheet_cell_comments}\n"
    summary_row

  end

  def WeeklyStatus.weekly_summary(weekly_status_id)
    sql = %Q{
      select *
      from weekly_status_details
      where weekly_status_details.weekly_status_id = ?
      order by timesheet_cell_project_code, timesheet_cell_project_title, timesheet_cell_task_name, timesheet_cell_work_date
    }

    details = WeeklyStatusDetail.find_by_sql [sql, weekly_status_id]
    $log.debug("in weekly summary with details #{details.to_a.count}")
    summary = []
    summary_row = {}

    if details.count > 0
      details.each do |row|
        pc = row.timesheet_cell_project_code
        tn = row.timesheet_cell_task_name
        daily_comment = "#{row.timesheet_cell_work_date.to_s}: #{row.timesheet_cell_comments}\n"

        if summary_row.empty?
          summary_row = build_summary_row(row)
        else
          # append comments if the project_code and task number is the same as the summary row
          if summary_row['timesheet_cell_project_code'].eql?(pc) && summary_row['timesheet_cell_task_name'].eql?(tn)
            summary_row['weekly_summary_comment'] << daily_comment
          else
            # add the summary_row to the array and build a new summary_row and continue looping
            summary << summary_row
            summary_row = build_summary_row(row)
          end
        end
      end
      # append on the last summary_row that was built
      summary << summary_row
    end
    summary
  end

=begin
  #    result = WeeklyStatus.greg(user_id: 4, week_start_date: '04/26/2020')
  #    load './app/models/weekly_status.rb'
  def self.query_example(user_id:, week_start_date:)
    sql = %Q{
      select * from (
        select week_start_date, project_organization, project_code, project_title, task_number, task, person, sum(hours) as hr, '' as summary_comment
        from  (
          select TO_CHAR(a.week_start_date, 'YYYY-MM-DD') as week_start_date, b.*
          from weekly_statuses a, weekly_status_details b
          where a.id = b.weekly_status_id
          and   a.user_id = ?
          and   a.active = true
          and   a.week_start_date = ?
        ) as sum_hours
        group by week_start_date, project_organization, project_code, project_title, task_number, task, person
      union all
        select distinct week_start_date as week_start_date, project_organization, project_code, project_title, task_number, task, person, 0 as hr, task_date || ': ' || coalesce(comments, null, '<empty comment>') as summary_comments
        from (
          select TO_CHAR(a.week_start_date, 'YYYY-MM-DD') as week_start_date, project_organization, project_code, project_title, task_number, task, person, task_date, comments
          from weekly_statuses a, weekly_status_details b
          where a.id = b.weekly_status_id
          and   a.user_id = ?
          and   a.active = true
          and   a.week_start_date = ?
          order by project_code, task_number, task_date
          ) as ordered_comments
        ) as summary_data
        order by project_code, task_number, hr
      }

    wsd = Date.strptime(week_start_date, '%m/%d/%Y')
    args = {user_id: 4, week_start_date: wsd, user_id2: 4, week_start_date2: wsd }
    binds = WeeklyStatus.resolve_sql_bindings(args)
    result = ApplicationRecord.connection.exec_query(sql, 'user_weekly_summary', binds)
    result.to_hash
  end
=end
  def self.resolve_sql_bindings(**args)
    bindings = []
    idx = 0
    args.each_pair do |name, value|
      idx = idx + 1
      if value.is_a? Integer
        bindings << ActiveRecord::Relation::QueryAttribute.new(name.to_s, value, ActiveRecord::Type::Integer.new)
      elsif value.is_a? String
        bindings << ActiveRecord::Relation::QueryAttribute.new(name.to_s, value, ActiveRecord::Type::String.new)
      elsif value.is_a?(TrueClass) || value.is_a?(FalseClass)
        bindings << ActiveRecord::Relation::QueryAttribute.new(name.to_s, value, ActiveRecord::Type::Boolean.new)
      elsif value.is_a? Float
        bindings << ActiveRecord::Relation::QueryAttribute.new(name.to_s, value, ActiveRecord::Type::Float.new)
      elsif value.is_a? Date
        bindings << ActiveRecord::Relation::QueryAttribute.new(name.to_s, value, ActiveRecord::Type::Date.new)
      elsif value.is_a? DateTime
        bindings << ActiveRecord::Relation::QueryAttribute.new(name.to_s, value, ActiveRecord::Type::DateTime.new)
      elsif value.is_a? Time
        bindings << ActiveRecord::Relation::QueryAttribute.new(name.to_s, value, ActiveRecord::Type::Time.new)
      else
        raise 'error - not supported'
      end
    end
    bindings
  end

  # result = WeeklyStatus.check_for_summaries(week_start_date: '04/12/2020')
  #    load './app/models/weekly_status.rb'
  def self.check_for_summaries
    sql = %Q{
      select id as weekly_status_id
      from weekly_statuses a
      where a.week_start_date = ?
      and not exists (
        select * from weekly_summaries b
        where a.id = b.weekly_status_id
      )
    }
    wsd = Date.strptime(week_start_date, '%m/%d/%Y')
    args = {week_start_date: wsd}
    binds = WeeklyStatus.resolve_sql_bindings(args)
    result = ApplicationRecord.connection.exec_query(sql, 'weekly_summaries_to_create', binds)
    result.to_hash
  end

  def create_summaries
    @local_summaries = self.weekly_summary(self.id)
  end

  def create_details
    @local_details = []
    earliest_date = 10.years.from_now.to_date

    @csv_data.by_row.each do |row|
      wsd = WeeklyStatusDetail.new
      wsd.person_timesheet_approval_group_name = row[PERSON_TIMESHEET_APPROVAL_GROUP_NAME].to_s.strip
      wsd.send(:person_last_name=, row[PERSON_LAST_NAME].to_s.strip)
      wsd.send(:person_first_name=, row[PERSON_FIRST_NAME].to_s.strip)
      wsd.send(:person_email_id=, row[PERSON_EMAIL_ID].to_s.strip)
      wsd.send(:person_default_pay_code=, row[PERSON_DEFAULT_PAY_CODE].to_s.strip)
      wsd.send(:timesheet_cell_project_code=, row[TIMESHEET_CELL_PROJECT_CODE].to_s.strip) #key uniq
      wsd.send(:timesheet_cell_task_name=, row[TIMESHEET_CELL_TASK_NAME].to_s.strip) #key uniq
      wsd.send(:timesheet_cell_project_title=, row[TIMESHEET_CELL_PROJECT_TITLE].to_s.strip) #key uniq

      work_date = Date.strptime(row[TIMESHEET_CELL_WORK_DATE].to_s.strip, '%m/%d/%Y')
      wsd.send(:timesheet_cell_work_date=, work_date)

      wsd.send(:timesheet_cell_hours=, row[TIMESHEET_CELL_HOURS].to_f)
      wsd.send(:timesheet_cell_comments=, row[TIMESHEET_CELL_COMMENTS].to_s.strip)

      wsd.weekly_status = self
      @local_details << wsd

      if work_date < earliest_date
        earliest_date = work_date
      end
    end

    self.week_start_date = Unanet.get_start_of_week(earliest_date)
  end
end


=begin
load './app/models/weekly_status.rb'
w = WeeklyStatus.all.last
 a = w.weekly_csv
 a.download
a.content_type
 a.download.split.first

# to get the latest summary upload (in case they uploaded multiple times for a given week)
 latest = WeeklyStatus.latest_start_of_week(Date.strptime('4/30/2 020', '%m/%d/%Y'), User.find(3))

=end

app/controllers/weekly_status_controller.rb
class WeeklyStatusController < ApplicationController
  before_action :verify_user_in_role!

  def index
    @weekly_statuses = WeeklyStatus.where('user_email = ?', current_user.email).order(week_start_date: :desc)
  end

  def show
    ws_id = params[:id]
    if WeeklySummary.find_by_weekly_status_id(ws_id).nil?
      init_weekly_summary ws_id
    end
    @weekly_status = WeeklyStatus.find(ws_id)
    verify_authorized(@weekly_status.user_email)
  end

  def details
    ws_id = params[:id]
    @details = WeeklyStatus.find(ws_id).weekly_status_details.order(timesheet_cell_project_code: :asc, timesheet_cell_task_name: :asc, timesheet_cell_work_date: :asc)
    verify_authorized(@details.first.person_email_id)
  end

  def update
    ws_id = params[:id]
    @weekly_status = WeeklyStatus.find(ws_id)

    if (@weekly_status.update_attributes(weekly_params))
      @weekly_status.reviewed_status!
      $log.debug("I updated the weekly summaries for #{ws_id}")
    else
      $log.error("I failed to update the weekly summaries for #{ws_id}")
    end
    redirect_to weekly_status_index_path
  end

  private

  def weekly_params
    params.require(:weekly_status).permit(
        weekly_summaries_attributes: %w(id reviewed weekly_summary_comment blockers next_planned_activity)
    # weekly_summaries_attributes: WeeklySummary.column_names
    )
  end

  # def weekly_params
  #   this is a permit all!!
  #   params.require(:weekly_status).permit! #.permit(get_whitelist)
  # end

  # def get_whitelist
  #   params_array = WeeklyStatus.column_names
  #   weekly_array = [:weekly_summaries_attributes => WeeklySummary.column_names]
  #   params_array << weekly_array
  # end

end

app/helpers/weekly_status_helper.rb
module WeeklyStatusHelper
  NOT_STARTED = {status: 'Not Started', image: 'bolt', color: 'red'} # not yet looked at - no rows in summary
  IN_PROCESS = {status: 'In Process', image: 'edit', color: 'green'} # some but not all summaries have been reviewed
  COMPLETED = {status: 'Completed', image: 'check', color: 'black'} # all summaries are reviewed

  def fetch_summary_status(weekly_status)
    if weekly_status.not_started?
      return NOT_STARTED
    elsif weekly_status.in_process?
      return IN_PROCESS
    end
    COMPLETED
  end
end

app/views/weekly_status/_wsr_row.html.erb
<div style="background-color: #3f57a6; color: white; border: #8b8b8b solid thin">
  <div style="float: right; color: navy">
    <a class="btn btn-tertiary" onclick="show_summary('weekly_status_weekly_summaries_attributes_<%= index %>_reviewed', <%= row.object.id %>)">Show/Hide Comments</a>
  </div>
</div>
<div class="container">
  <div class="row">
    <div class="col-sm">
      <%= span_label('Project Code') %>
      <%= row.object.timesheet_cell_project_code %>
    </div>
    <div class="col-sm">
      <%= span_label('Project Title') %>
      <%= row.object.timesheet_cell_project_title %>
    </div>
    <div class="col-sm">
      <%= span_label('Task Name') %>
      <%= row.object.timesheet_cell_task_name %>
    </div>
  </div>
  <hr>
  <div id="toggle_<%=row.object.id %>" class="comments-edit">
    <div class="row">
      <div class="col-sm">
        <%=label_tag :weekly_summary_comment, 'Weekly Summary Comment:' %>
        <%= row.text_area :weekly_summary_comment, class: 'summary-text-area'  %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm">
        <%=label_tag :blockers, 'Blockers:' %>
        <%= row.text_area :blockers, class: 'summary-text-area' %>
      </div>
    </div>
    <div class="row">
      <div class="col-sm">
        <%=label_tag :next_planned_activity, "Next Planned Activity:"  %>
        <%= row.text_area :next_planned_activity, class: 'summary-text-area' %><!-- todo what is summary-text-area class?! -->
      </div>
    </div>
  </div>
</div>
<script type="text/javascript" charset="utf-8">
    function  show_summary(selector, id) {
        console.log("selector", selector);
        $('#' + selector).val(true);
        $('#toggle_'+ id).toggle();
    }
  // initially hide all comment fields so the act of showing will allow us to set the reviewed hidden field to true
  $(document).ready(function(){
      $('.comments-edit').hide();
  });
</script>

app/views/weekly_status/details.html.erb
<%=link_to 'Back', weekly_status_index_path, class: 'btn btn-primary' %><br><br>
<h3>Weekly Status Details for <%= @details.first.weekly_status.week_start_date %></h3>
<table class="table">
  <thead class="thead-light">
  <tr>
    <th>Project Code</th>
    <th>Project Title</th>
    <th>Task Number:Title</th>
    <th>Task Date</th>
    <th>Hours</th>
    <th colspan="2">Comment</th>
  </tr>
  </thead>
  <tbody>
    <% @details.each do |row| %>
      <tr>
        <td><%= row.timesheet_cell_project_code %></td>
        <td><%= row.timesheet_cell_project_title %></td>
        <td><%= row.timesheet_cell_task_name %></td>
        <td><%= row.timesheet_cell_work_date %></td>
        <td><%= row.timesheet_cell_hours %></td>
        <td><%= row.timesheet_cell_comments %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/weekly_status/index.html.erb
<div class="container">
  <br>
  <h4>Weekly Summaries for <%= current_user.email %></h4>
  <br>
  <table class="table" style="width: fit-content">
    <thead class="thead-light">
    <tr>
      <th>Week Start Date</th>
      <th>Week End Date</th>
      <th>Review Status</th>
      <th colspan="2" style="text-align: center">Actions</th>
    </tr>
    </thead>
    <tbody>
    <% @weekly_statuses.each do |weekly_status| %>
    <%status = fetch_summary_status weekly_status %>
      <% icon = "fas fa-#{status[:image]}" %>
      <tr>
        <td><%= weekly_status.week_start_date %></td>
        <td><%= weekly_status.week_start_date + 6 %></td>
        <td><i class="<%= icon %>"></i>&nbsp;&nbsp;<span style="font-weight: bold; <%= "color: #{status[:color]}" %>"><%= status[:status] %></span></td>
        <td><%= link_to 'Edit Summary', weekly_status_path(weekly_status) %></td>
        <td><%= link_to "List Details", :controller => "weekly_status", :action => "details", :id => weekly_status %></td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

app/views/weekly_status/magic_upload.html.erb
<h1>Magic Results</h1>
<%= @result if @result.eql?('sad') %>

<table style="width: 9000px">
  <tr>
    <thead>
    <% @headers.each do |hdr| %>
      <th><%= hdr %></th>
    <% end %>
    </thead>
  </tr>
  <% @rows.each do |row| %>
    <tr>
      <% row.each do |col| %>
        <td><%= col.last %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/weekly_status/show.html.erb
<h1>Weekly Summary for <%= @weekly_status.week_start_date %></h1>
<%= form_for(@weekly_status, :url => {:controller => "weekly_status", :action => "update"}) do |f| %>
  <%= f.fields_for :weekly_summaries, f.object.weekly_summaries.order(:timesheet_cell_project_code, :timesheet_cell_task_name) do |builder| %>
    <% @count ||= -1; @count += 1 %>

    <div style="background-color: <%= (@count % 2).odd? ? 'lightblue' : 'cornsilk' %>">
      <%= builder.hidden_field :reviewed %>
      <%= render partial: "weekly_status/wsr_row", locals: {row: builder, index: @count} %>
      <br>
    </div>
  <% end %>
  <br>
  <div>
    <%= link_to 'Cancel', weekly_status_index_path, class: 'btn btn-secondary' %>
    <%= submit_tag 'Save Summary', class: 'btn btn-primary' %></div>
<% end %>