config/routes.rb
Rails.application.routes.draw do
  resources :recipes
  resources :weekly_status

  get 'admin_upload/index'
  post  "admin_upload" =>'admin_upload#upload'

  get 'project_mgr/index'
  post  "project_mgr/summaries" =>'project_mgr#summaries'


  get  "weekly_status_index" =>'weekly_status#index'

  match '/weekly_status_details/:id' => 'weekly_status#details', via: :get
  post  "magic_upload" =>'weekly_status#magic_upload'
  post  "weekly_status_upload" =>'weekly_status#upload'

  patch  "weekly_summary_update" =>'weekly_status#update'

  devise_for :users
  post 'fetch_time' => 'react_component#fetch_time'

  %w(account rec_engine).each { |path|
    get "/#{path}" => 'react_component#auth'
  }


  %w(awaiting_approval).each { |path|
    get "/#{path}" => 'react_component#awaiting_approval'
  }


  root :to => 'layouts#root'

end

app/controllers/layouts_controller.rb
class LayoutsController < ApplicationController
  # this is the root route for the application
  def root
  end

  def form_inputs
    render json: {recieved: params}
  end
end

app/views/layouts/_footer.html.erb
<div class="footer-container">
  <footer>
    <div class="logo" aria-label="VA Logo">
      <a href="https://www.va.gov" title="Go to VA.gov">
        <img style="vertical-align: middle" src="<%= asset_pack_path 'media/packs/images/va-logo-white.png' %>"  alt="VA Header Image"/>
      </a>
    </div>
    <div>
      <nav role="navigation" aria-label="External Links Navigation">
        <ul>
          <li><a href="https://www.section508.va.gov" title="Accessibility" class='link'>Accessibility</a></li>
          <li><a href="https://www.va.gov/orm/NOFEAR_Select.asp" title="No FEAR Act Data" class='link'>No FEAR Act Data</a></li>
          <li><a href="https://www.va.gov/opa/Plain_Language.asp" title="Plain Language" class='link'>Plain Language</a></li>
          <li><a href="https://www.va.gov/oig/" title="Office of Inspector General" class='link'>Office of Inspector General</a></li>
          <li><a href="https://www.usa.gov/" title="USA.gov" class='link'>USA.gov</a></li>
          <li><a href="https://www.va.gov/privacy-policy/" title="Privacy, Policies &amp; Legal information" class='link'>Privacy, Policies &amp; Legal information</a></li>
          <li><a href="https://www.va.gov/foia/" title="Freedom of Information Act (FOIA)" class='link'>Freedom of Information Act (FOIA)</a></li>
          <li><a href="https://www.va.gov/privacy/" title="VA Privacy Service" class='link'>VA Privacy Service</a></li>
          <li><a href="https://www.va.gov/scorecard/" title="VA.gov scorecard" class='link'>VA.gov scorecard</a></li>
          <li><a href="https://www.va.gov/veterans-portrait-project/" title="Veterans Portrait Project" class='link'>Veterans Portrait Project</a></li>
        </ul>
      </nav>
    </div>
  </footer>
</div>

app/views/layouts/_header.html.erb
<div class="header-container">
  <header>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="navbar-brand" href="#">
        <img style="vertical-align: middle" src="<%= asset_pack_path image('vetsez-logo.png') %>" alt="VetsEZ Logo"/>
      </div>
      <!--        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">-->
      <!--          <span class="navbar-toggler-icon">what!</span>-->
      <!--        </button>  ??? what does this do?  -->

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <%= link_to 'Home', root_path, class: 'nav-link' %>
          </li>
          <% if current_user&.has_role? Roles::RoleTags::CONTRIBUTOR_ROLE %>
            <li class="nav-item">
              <%= link_to 'Weekly Summaries', weekly_status_index_path, class: 'nav-link' %>
            </li>
          <% end %>
          <% if current_user&.has_role? Roles::RoleTags::ADMIN_ROLE %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Administration
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "CSV Upload", admin_upload_index_path, class: 'dropdown-item' %>
                <!--                <div class="dropdown-divider"></div>-->
              </div>
            </li>
          <% end %>

          <% if current_user&.has_role? Roles::RoleTags::PM_ROLE %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                PM Menu
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <%= link_to "PM WSR Summaries", project_mgr_index_path, class: 'dropdown-item' %>
              </div>
            </li>
          <% end %>
        </ul>
        <form class="my-2 my-lg-0">
          <% if (current_user) %>
            <h5>Welcome <%= current_user&.email %>!<br></h5>
            <div style="float: right">
              <%= link_to 'Logout', destroy_user_session_path %>
            </div>
          <% else %>
            <div style="float: right">
              <%= link_to 'Login', new_user_session_path %>&nbsp;|&nbsp;
              <%= link_to 'Signup', new_user_registration_path %>
            </div>
          <% end %>
        </form>
      </div>
    </nav>
  </header>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |key, value| %>
  <!-- we are only displaying errors (flash.error on access issues. All other flashes are using $.notify below -->
  <% if key == 'error' %>
    <div class="container" role="alert">
      <div id="error_explanation" class="usa-alert usa-alert-error" role="alert">
        <div class="usa-alert-body">
          <h3 class="usa-alert-heading"><%= key.capitalize %> </h3>
          <p><%= value %></p>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
<script type="text/javascript" charset="utf-8">
  $(document).ready(function () {
    <% flash.each do |key, value| %>
      let type = '<%= key.eql?('notice') ? 'success' : 'danger'  %>';

      <% if key != 'error' %>
        $.notify('<%=value %>', {type: type});
      <% end %>
    <% end %>
  });
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>VetsEZ Works Weekly Reporting</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= include_gon %>
  <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" data-auto-replace-svg="nest"></script>
  <%= javascript_pack_tag 'javascripts/application.js' %>
  <%= javascript_include_tag 'application' %>
  <!-- cris -->
  <%= stylesheet_pack_tag 'stylesheets/application.css' %>
</head>
<body>
<%= render 'layouts/header' %>
<div class="main container-fluid">
  <div class="row">
<!--    <div class="col-sm-2 py-2">-->
<!--      <nav class="nav flex-column">-->
        <%#= link_to "Admin CSV Upload", admin_upload_index_path, class: 'nav-link' %>
<!--      </nav>-->
<!--    </div>-->
    <div class="col-sm-12">
      <%= render 'layouts/messages' %>
      <%= yield %>
    </div>
  </div>
</div>
</body>
</html>

app/views/layouts/root.html.erb
<div class="container p-4">
  <% if current_user %>
    <div>
      <h2>Welcome <%= current_user.email %></h2>
      <p>Please use the navigation menu above to enter your weekly status summaries.</p>
    </div>

  <% else %>
    <div>
      <h2>Landing Page</h2>
      <p>not logged in</p>
    </div>
  <% end %>
</div>